export const products = [
  {
    id: 1,
    name: 'Galleta Chip Chocolate',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 2,
    name: 'Pan Hamburguesa Brioche c/semilla x 4 u.',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 3,
    name: 'Pan Hamburguesa Brioche papa c/hebras x 4 u.',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 4,
    name: 'Pan lactal común blanco',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 5,
    name: 'Pan lactal común negro',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 6,
    name: 'Pan lactal con semilla',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 7,
    name: 'Palmerita',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 8,
    name: 'Rosquillas',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 9,
    name: 'Semoladas c/semillas',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 10,
    name: 'Semoladas comun',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 11,
    name: 'Pan chip x 12 u.',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 12,
    name: 'Pan pebete x 6 u.',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 13,
    name: 'Pan Brioche Viena x 6 u.',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 14,
    name: 'Tarta cabsha x 4 u.',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 15,
    name: 'Alfajor maizena x 12 u.',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 16,
    name: 'Bizcocho grasa x 1 kg',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 17,
    name: 'Hamburguesa Paladini 2x80gr (pack)',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 18,
    name: 'Mostaza Danica Fiesta x 220gr',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 19,
    name: 'Mayones Hellmans x 237gr',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 20,
    name: 'Bolsas plastico 20x30',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 21,
    name: 'Pan lactal artesanal',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 22,
    name: 'Pan lactal integral',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 23,
    name: 'Pan Hamburguesa tipo campo x 4 u.',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 24,
    name: 'Pan hamburguesa común x 4 u.',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 25,
    name: 'Patitas de pollo comune x 5 kg GRANGYS',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 26,
    name: 'Patitas de pollo J y Q x 5 kg GRANGYS',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 27,
    name: 'Crocante de pollo GRANGYS',
    price: 10.99,
    image: '/images/product1.jpg',
  },
  {
    id: 28,
    name: 'Bocadito Calabaza y muzzarella GRANGYS',
    price: 12.99,
    image: '/images/product2.jpg',
  },
  {
    id: 29,
    name: 'Pan Chip Comun x 1kg',
    price: 10.99,
    image: '/images/product1.jpg',
  },
];
