export const products = [
  {
    id: 1,
    name: 'Galleta Chip Chocolate x 100 gr',
    price: 800,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 2,
    name: 'Pan Hamburguesa Brioche c/semilla x 4 u.',
    price: 2000,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 3,
    name: 'Pan Hamburguesa Brioche papa c/hebras x 4 u.',
    price: 2300,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 4,
    name: 'Pan lactal común blanco',
    price: 2900,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Panes lactales',
  },
  {
    id: 5,
    name: 'Pan lactal común negro',
    price: 2900,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Panes lactales',
  },
  {
    id: 6,
    name: 'Pan lactal blanco con semilla',
    price: 3600,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Panes lactales',
  },
  {
    id: 7,
    name: 'Palmeritas x 100 gr',
    price: 1000,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 8,
    name: 'Rosquillas x 100 gr',
    price: 1000,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 9,
    name: 'Semoladas c/semillas',
    price: 650,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 10,
    name: 'Semoladas comun',
    price: 650,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 11,
    name: 'Pan chip x 12 u.',
    price: 3400,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 12,
    name: 'Pan pebete x 6 u.',
    price: 2500,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 13,
    name: 'Pan Brioche Viena x 6 u.',
    price: 2000,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 14,
    name: 'Tarta cabsha x 4 u.',
    price: 1500,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 15,
    name: 'Alfajor maizena x 12 u.',
    price: 1000,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 16,
    name: 'Bizcocho grasa x 1 kg',
    price: 700,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Galletas y variedades',
  },
  {
    id: 17,
    name: 'Hamburguesa Paladini 2x80gr (pack)',
    price: 10.99,
    image: '/images/product1.jpg',
    active: false,
    categories: 'Pan para sanguchess',
  },
  {
    id: 18,
    name: 'Mostaza Danica Fiesta x 220gr',
    price: 12.99,
    image: '/images/product2.jpg',
    active: false,
    categories: '',
  },
  {
    id: 19,
    name: 'Mayones Hellmans x 237gr',
    price: 10.99,
    image: '/images/product1.jpg',
    active: false,
    categories: '',
  },
  {
    id: 20,
    name: 'Bolsas plastico 20x30',
    price: 12.99,
    image: '/images/product2.jpg',
    active: false,
    categories: '',
  },
  {
    id: 21,
    name: 'Pan lactal artesanal',
    price: 3900,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Panes lactales',
  },
  {
    id: 22,
    name: 'Pan lactal integral',
    price: 3900,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Panes lactales',
  },
  {
    id: 23,
    name: 'Pan Hamburguesa tipo campo x 4 u.',
    price: 2100,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 24,
    name: 'Pan hamburguesa común x 4 u.',
    price: 1800,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 25,
    name: 'Patitas de pollo comunes GRANGYS x kg',
    price: 7000,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Congelados',
  },
  {
    id: 26,
    name: 'Patitas de pollo J y Q  GRANGYS x kg',
    price: 8000,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Congelados',
  },
  {
    id: 27,
    name: 'Crocante de pollo GRANGYS x Kg',
    price: 8700,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Congelados',
  },
  {
    id: 28,
    name: 'Bocadito Calabaza y muzzarella GRANGYS x Kg',
    price: 6500,
    image: '/images/product2.jpg',
    active: true,
    categories: 'Congelados',
  },
  {
    id: 29,
    name: 'Pan Chip Comun x 1kg',
    price: 5200,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Pan para sanguchess',
  },
  {
    id: 30,
    name: 'Bocadito Papa y Queso GRANGYS x Kg',
    price: 6500,
    image: '/images/product1.jpg',
    active: true,
    categories: 'Congelados',
  },
];
